// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/jipark0716/fcm-sender/firebase"
	"github.com/jipark0716/fcm-sender/kafka"
)

// Injectors from wire.go:

func InitFirebaseMessageService(k *kafka.Config, f *firebase.Config) *firebase.MessageService {
	messageService := firebase.NewMessageService(k)
	return messageService
}
